# Header
menu:
  主页: /
  所有文章: /archives
  前端开发: /categories/前端开发
  随笔: /categories/随笔

# SubNav
subnav:
  #github: "#"
  #weibo: "#"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "/img/photo.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

leancloud:
    enable: true
    app_id: VQn5LA68eTXK10eIfhhgwi6O-gzGzoHsz
    app_key: tmuVrxGxQRXVn6ueMbaIkcfW
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
 # 习大大大不同: http://localhost:4000/
 # 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 野生前端，科幻迷，业余天文爱好者